# Generated by Django 4.0.6 on 2022-09-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=50, verbose_name='Автор поста'),
        ),
    ]
