# Generated by Django 4.0.6 on 2023-01-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile_slug_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
