# Generated by Django 4.0.6 on 2023-01-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
