# Generated by Django 4.0.6 on 2023-01-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_friendrequest_from_user_friendrequest_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='to_user',
        ),
    ]
