# Generated by Django 4.0.6 on 2023-01-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
