# Generated by Django 4.0.6 on 2023-01-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
